version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '8000:8000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - backend
  redis:
    image: redis:4
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
  